Repository 8percent/rdb-study, pull requests merged in 2021-12, with the labels that each got.

#27 [W1] 윤 문제 풀이
  chapter1/exercise_yun.md
  chapter2/exercise_yun.md
  chapter3/exercise_yun.md
Labels: W1

#6 [W1] 민기 문제 풀이
  chapter1/exercise_minki.md
  chapter2/exercise_minki.md
  chapter3/exercise_minki.md
Labels: W1

#26 [W1] 택천 문제 풀이
  chapter1/exercise_taekcheon.md
  chapter2/exercise_taekcheon.md
  chapter3/exercise_taekcheon.md
Labels: W1

#29 [W1] 동현 문제 풀이
  chapter1/exercise_donghyun.md
  chapter2/exercise_donghyun.md
  chapter3/exercise_donghyun.md
Labels: W1

#28 [W1] 준식 문제 풀이
  chapter1/exercise_joonshik.md
  chapter2/exercise_joonshik.md
  chapter3/exercise_joonshik.md
Labels: W1

#13 [W1] 호성 문제 풀이
  chapter1/exercise_hosung.md
  chapter2/exercise_hosung.md
  chapter3/exercise_hosung.md
Labels: W1

#25 [W1] 우주 문제 풀이
  chapter1/exercise_wooju.md
  chapter2/exercise_wooju.md
  chapter3/exercise_wooju.md
Labels: W1

#40 [W1] 진영 문제 풀이
  chapter1/exercise_jinyoung.md
  chapter2/exercise_jinyoung.md
  chapter3/exercise_jinyoung.md
Labels: W1

#37 [W1] 명욱 문제 풀이
  chapter1/exercise_myungwook.md
  chapter2/exercise_myungwook.md
  chapter3/exercise_myungwook.md
Labels: W1

#38 [W1] 경준 문제 풀이
  .gitignore
  chapter1/exercise_kyungjun.md
  chapter1/비교.png
  chapter2/exercise_kyungjun.md
  chapter3/exercise_kyungjun.md
  chapter3/integrity.png
Labels: W1

#45 [W2] 호성 문제 풀이
  chapter4/exercise_hosung.md
  chapter5/exercise_hosung.md
  chapter6/exercise_hosung.md
Labels: W2

#55 [W2] 진영 문제풀이
  chapter4/exercise.md
  chapter5/exercise.md
  chapter6/exercise.md
Labels: W2

#53 [W2] 경준 문제 풀이
  chapter4/exercise_kyungjun.md
  chapter5/exercise_kyungjun.md
  chapter6/exercise_kyungjun.md
  chapter7/exercise_kyungjun.md
Labels: W2

#52 [W2] 준식 문제풀이
  chapter4/exercise_joonshik.md
  chapter5/exercise_joonshik.md
  chapter6/exercise_joonshik.md
Labels: W2

#51 [W2] 명욱 문제풀이
  .gitignore
  chapter4/exercise_myungwook.md
  chapter5/exercise_myungwook.md
  chapter6/exercise_myungwook.md
Labels: W2

#50 [W2] 윤 문제 풀이
  chapter4/exercise_yun.md
  chapter5/exercise_yun.md
  chapter6/exercise_yun.md
Labels: W2

#49 [W2] 동현 문제 풀이
  chapter4/exercise_donghyun.md
  chapter5/exercise_donghyun.md
  chapter6/exercise_donghyun.md
Labels: W2

#48 [W2] 민기 문제 풀이
  chapter4/exercise_minki.md
  chapter5/exercise_minki.md
  chapter6/exercise_minki.md
Labels: W2

#47 [W2] 우주 문제 풀이
  chapter4/exercise_wooju.md
  chapter5/exercise_wooju.md
  chapter6/exercise_wooju.md
Labels: W2

#46 [W2] 택천 문제 풀이
  chapter1/exercise_taekcheon.md
  chapter4/exercise_taekcheon.md
  chapter5/exercise_taekcheon.md
  chapter6/exercise_taekcheon.md
Labels: W2

#57 NEW: 7~9 챕터 문제 추가
  chapter7/exercise.md
  chapter8/exercise.md
  chapter9/exercise.md
Labels: W3
