Repository 8percent/rdb-study, pull requests merged in 2022-01, with the labels that each got.

#63 [W4] 명욱 문제풀이
  chapter7/exercise_myungwook.md
  chapter8/exercise_myungwook.md
  chapter9/exercise_myungwook.md
Labels: W4

#60 [W4] 준식 문제 풀이
  chapter7/exercise_joonshik.md
  chapter8/exercise_joonshik.md
  chapter9/exercise_joonshik.md
Labels: W3

#70 [W5] 민기 문제풀이
  chapter10/exercise_minki.md
  chapter11/exercise_minki.md
  chapter12/exercise_minki.md
Labels: W5

#69 [W5] 우주 문제풀이
  chapter10/exercise_wooju.md
  chapter11/exercise_wooju.md
  chapter12/exercise_wooju.md
Labels: W4

#67 [W5] 호성 문제풀이
  chapter10/exercise_hosung.md
  chapter11/exercise_hosung.md
  chapter12/exercise_hosung.md
Labels: W4

#73 [W5] 명욱 문제풀이
  chapter10/exercise_myungwook.md
  chapter11/exercise_myungwook.md
  chapter12/exercise_myungwook.md
Labels: W5
